### ISSUE TITLE
add mana curve v base mana supply analysis

### ISSUE THREAD

**Issue by svidgen** [svidgen/mtg.deckanalyzer.com-Feedback#11]
Show a standard-ish mana curve alongside or overlaid with a base mana supply (mana from land).

**Comment by Alambre020** [comment]
highlight thibgs that cost mutilple colored mana

**Comment by svidgen** [comment]
Basic mana curve is done. TODO: A _basic_ mana demand v. supply graph.

**Comment by svidgen** [comment]
I think the basics are covered here. I'm still trying to work out a UI to compare [base] mana supply v. demand in a meaningful/helpful way -- which I'll churn on for a little while. If I can't come up with something soon, I'll close this and break off another issue for the enhancement.

**Comment by svidgen** [comment]
OK. I think we've got something that works. Closing...
