### ISSUE TITLE
Mulligan advice

### ISSUE THREAD

**Issue by svidgen** [svidgen/mtg.deckanalyzer.com-Feedback#35]
Summarize the indicators on decks for when a Mulligan should be taken and what the combined and individual odds are of hitting P(P) between first draw and Mulligan(s).

**Comment by Alambre020** [comment]
Na'ice!  I will have to check that out.

**Comment by svidgen** [comment]
Yep. It's just a concept right now. Calculating odds for a mulligan is relatively straightforward.

I'm not yet sure how I'm going to read and summarize the indicators of a doomed draw. It'll have to report by card category/tactic, at least primarily. Beyond that, I'm not sure whether I should include a land/mana-cost assessment -- or if I should leave it solely on the player to define any land requirements they want as part of the guidance.

**Comment by mack0331** [comment]
Doesn't the API that you use include "Card Type" (Land, Creature, etc.)?
Each deck could have something that works similar to Tactics in that you
can set the "Need X lands by turn Y". But it could be a single setting for
each deck that you set separate from the Tactics. If it's not tied to a
Tactic where you have to manually add cards to the group, you could make an
automatic Land-Tactic sort of of thing that generates based on the number
of "Card Type = Land". This way, as you edit the deck, the
mulligan/mana-screw/mana-flood percentages are automatically created.

**Comment by svidgen** [comment]
Yep, the card data is sufficient for a basic mana assessment. But, it gets tricky factoring in other mana producers. Maybe that's where this other UI you're talking about comes into play, but I don't think I get what you mean exactly.

I've had in the back my mind the idea of just adding other flags/box under each card for tagging mana production -- which could then feed into the existing mana curve analysis more meaningfully too. Is something like that what you had in mind?

That might have to be a separate feature though. There's a lot of work that'll probably have to go into making that produce *meaningful* numbers. I.e., a mana producer isn't *really* a mana producer if you haven't had enough mana to play it yet!

**Comment by mack0331** [comment]
Mana producers (i.e. cards that you have to cast to get onto the
battlefield to help you produce additional mana) would, in my estimation,
not be taken into account at all when considering mulligans. I think it
would be more appropriate for someone to just create a tactic (e.g. Mana
Ramp/Mana Acceleration) for those cards. I'm not necessarily envisioning a
new UI, just stats that are generated based on readily available data about
the cards themselves--no tactic need be assigned.

Can you clarify what card data you have access to? If you can tell if
something is a Land or not, that's probably all you need, IMO.

**Comment by svidgen** [comment]
I'm pretty sure everything printed on the cards, aside from the actual artwork, is available. Card types/subtypes are broken into their own fields. So, that's easy to extract -- currently used for both the mana stats and assigning "card score" for auto-pruning suggestions.

**Comment by svidgen** [comment]
Card data is pulled from http://mtgjson.com/

**Comment by svidgen** [comment]
Done in a rudimentary form. Plenty of room to improve, but, I think this is sufficient for now.

Added a "keep" column to show the range in which you're odds of hitting P(All) are roughly greater than that of a mulligan:
![Screen Shot 2019-04-19 at 11 51 15 PM](https://user-images.githubusercontent.com/8375502/56452902-21cfea00-62fe-11e9-923b-1aaa237f0959.png)

Add a pop-up chart showing the actual P(All) rates *given a number of cards matching a tactic in hand*:
![Screen Shot 2019-04-19 at 11 51 23 PM](https://user-images.githubusercontent.com/8375502/56452903-21cfea00-62fe-11e9-8367-87458dafcd36.png)
