### ISSUE TITLE
Debounce on card searches

### ISSUE THREAD

**Issue by mambazo1** [svidgen/mtg.deckanalyzer.com-Feedback#38]
It would be beneficial to implement a debounce when adding cards. Currently as you type a card name, it will perform an ajax query for every letter you type.

e.g.

A
Ar
Ara
Arah
Arahb
Arahbo

e.t.c.

This is eating up bandwidth and slowing the interface down considerably.

**Comment by svidgen** [comment]
Ok. Thanks for pointing out the performance aspect of this. I haven't observed that in my test configurations. But, the performance impact you're seeing makes sense.

I think this makes sense to get into the next sprint.

**Comment by svidgen** [comment]
Simplistic debounce has been added and should be deployed shortly.

Thanks for the suggestion!
