### ISSUE TITLE
Aerial Assault, WHAT!!!

### ISSUE THREAD

**Issue by ImpArts** [svidgen/mtg.deckanalyzer.com-Feedback#41]
I was looking up the cards in my deck (I'm new to the game) to learn more about them; when I got to Aerial Assault (W, sorcery, cmc 3, common) I near had a heart attack when I saw the value, $10,000.00!!! 
Please tell me this is a typo!

I'm going over here until I learn how to breathe again!

**Comment by svidgen** [comment]
Hey @ImpArts,

I don't think it's a typo on our side! We pull our pricing data directly from TCGPlayer's API. It's possible a vendor on their end entered a typo, which could potentially flow through the API. I honestly have no idea how TCGPlayer sanitizes pricing data *if at all*.

But, showing with a reasonable price range again: [TCG 0.01 0.21 5.00](https://mtg.deckanalyzer.com/?cards/Aerial%20Assault).

Let me know if you see different!

Thanks!
