### ISSUE TITLE
Add support for commander/s

### ISSUE THREAD

**Issue by tucktuck101** [svidgen/mtg.deckanalyzer.com-Feedback#42]
Would be a great resource for edh.

Add them in as a category, exclude them from total deck count.

**Comment by svidgen** [comment]
Basic commander support has launched!

When you have a legendary creature in your deck, you can now expand that card and click the **Promote to Commander** button to select your commander.

![image](https://github.com/svidgen/mtg.deckanalyzer.com-Feedback/assets/8375502/f7f3f0ef-61b4-4863-ab0f-2e4efa5a7bbf)

This will move your commander to the top of the list and show a small "crossed swords" emoji to signify which card is your commander.

![image](https://github.com/svidgen/mtg.deckanalyzer.com-Feedback/assets/8375502/a4b5177e-dcf8-4a01-ab45-cfe50e1be99d)

If you want to remove the commander, "demote" the card with the **Demote from Commander** button.

![image](https://github.com/svidgen/mtg.deckanalyzer.com-Feedback/assets/8375502/cb87690c-e1e6-498e-9929-387fdd877c50)

I'm not enforcing any commander rules at the moment. It's up to you to ultimately build a valid deck. But, while a card is designated as a commander, the analysis accounts for this by assuming your commander is always available to play as though it were an extra card in your hand.

Happy to hear feedback on the update here. If there are bugs or major new commander-related features you'd like, please open new issues for them! But, hopefully this does the trick for folks.
