### ISSUE TITLE
Adding "*" to deck title hides and/or deletes saved deck

### ISSUE THREAD

**Issue by idikew** [svidgen/mtg.deckanalyzer.com-Feedback#51]
Hello! Thank you for creating and maintaining this useful site! 

I noticed that when I add an asterisk symbol to the end of a deck name when using the "rename" feature, it causes that deck to either disappear and/or become deleted. Is there a way to patch this. And on a related note, is there a way to recover the deck that I lost in this manner? 

Thanks!

**Comment by svidgen** [comment]
Thanks for reporting this. Do you know what you tried renaming the deck to?

**Comment by idikew** [comment]
Thank you for your reply! I was trying to rename the deck to: Boros Solar
Flare (Standard – Control) *

**Comment by svidgen** [comment]
@idikew I am really sorry to say the deck was lost during the broken rename. 😞

I'm not sure why my storage provider chokes on asterisks. But, going forward, I've corrected the rename operation to filter asterisks out and operate more safely in general.

I really appreciate you reporting this so I could get it fixed. For your time and trouble, I'd like to offer you free Pro service. It's still in beta, but I'm working on some really great updates to it as we speak. Hopefully it makes up for your lost time!

I'll apply the Pro features to your account shortly. If you don't see the take affect within an hour, please reach out to me at jon@deckanalyzer.com.

**Comment by idikew** [comment]
Hey, no worries at all, I was able to rebuild my deck pretty easily. :)

Thank you for the Pro offer, that's really generous of you!
